#
# Copyright (c) 2026 DenaryDev
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
group = me.denarydev.crystal
baseVersion = 3.0
description = The main library for my plugins

org.gradle.caching = false
org.gradle.parallel = true
