[versions]
# Platforms
paper = "1.21.10-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"
core = "1.1.0"

# Configs
configurate = "4.2.0"
configlib = "4.6.3"

# Plugins
skinsrestorer = "15.7.7"

# SQL
hikari = "7.0.2"
## Local
sqlite = "3.51.0.0"
h2 = "2.4.240"
## Remote
mysql = "9.5.0"
mariadb = "3.5.6"
postgresql = "42.7.8"

# Shared
slf4j = "2.0.17"
annotations = "26.0.2-1"

# Tests
junit = "6.0.1"
mockbukkit = "4.98.0"

[libraries]
# Platforms
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
core = { module = "ru.prostocraft.core:core", version.ref = "core" }

# Configs
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
configlib-core = { module = "de.exlll:configlib-core", version.ref = "configlib" }
configlib-yaml = { module = "de.exlll:configlib-yaml", version.ref = "configlib" }

# Plugins
skinsrestorer = { module = "net.skinsrestorer:skinsrestorer-api", version.ref = "skinsrestorer" }

# SQL
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
## Local
driver-sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
driver-h2 = { module = "com.h2database:h2", version.ref = "h2" }
## Remote
driver-mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
driver-mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
driver-postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

# Shared
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

# Tests
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
mockbukkit = { module = "org.mockbukkit.mockbukkit:mockbukkit-v1.21", version.ref = "mockbukkit" }

[bundles]
sql-drivers = ["driver-sqlite", "driver-h2", "driver-mysql", "driver-mariadb", "driver-postgresql"]
configurate = ["configurate-hocon", "configurate-yaml"]
