[versions]
# Platforms
paper = "1.21.10-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"
core = "1.1.0"

# Configs
configurate = "4.3.0-DEV-SNAPSHOT" # Версия из нашего репозитория с поддержкой комментариев в yaml файлах

# Plugins
skinsrestorer = "15.7.7"

# SQL
hikari = "7.0.2"
## Local
sqlite = "3.51.0.0"
h2 = "2.4.240"
## Remote
mysql = "9.5.0"
mariadb = "3.5.6"
postgresql = "42.7.8"

# Shared
slf4j = "2.0.17"
annotations = "26.0.2-1"

# Tests
mockbukkit = "4.98.0"

# Plugins
buildconfig = "5.6.7"
plugin-yml = "0.8.0"
run-task = "3.0.2"

[libraries]
# Platforms
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
core = { module = "ru.prostocraft.core:core", version.ref = "core" }

# Configs
configurate-core = { module = "io.sapphiremc.lib:configurate-core", version.ref = "configurate" }
configurate-hocon = { module = "io.sapphiremc.lib:configurate-hocon", version.ref = "configurate" }
configurate-yaml = { module = "io.sapphiremc.lib:configurate-yaml", version.ref = "configurate" }

# Plugins
skinsrestorer = { module = "net.skinsrestorer:skinsrestorer-api", version.ref = "skinsrestorer" }

# SQL
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
## Local
driver-sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
driver-h2 = { module = "com.h2database:h2", version.ref = "h2" }
## Remote
driver-mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
driver-mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
driver-postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

# Shared
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

# Tests
mockbukkit = { module = "org.mockbukkit.mockbukkit:mockbukkit-v1.21", version.ref = "mockbukkit" }

[bundles]
sql-drivers = ["driver-sqlite", "driver-h2", "driver-mysql", "driver-mariadb", "driver-postgresql"]
configurate = ["configurate-hocon", "configurate-yaml"]

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
pluginyml = { id = "de.eldoria.plugin-yml.paper", version.ref = "plugin-yml" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "run-task" }
