/*
 * Copyright (c) 2026 DenaryDev
 *
 * Use of this source code is governed by an MIT-style
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/MIT.
 */
package me.denarydev.crystal.database.query;

import me.denarydev.crystal.database.connection.ConnectionPool;
import me.denarydev.crystal.database.query.set.ResultSetMapper;
import me.denarydev.crystal.database.query.set.ResultSetWrapper;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.NotNull;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.Optional;

/**
 * Представляет SQL-запрос с параметрами для заполнения плейсхолдеров.
 */
public abstract class AbstractQuery {

    @NotNull
    protected final ConnectionPool pool;

    @ApiStatus.Internal
    protected AbstractQuery(@NotNull ConnectionPool pool) {
        this.pool = pool;
    }

    /**
     * @return SQL-запрос.
     */
    public abstract String getSQL();

    /**
     * @return Значения параметров запроса в порядке их появления (обозначаются символом <code>?</code> в SQL-запросе).
     */
    public abstract List<Object> getParams();

    /**
     * Создает подготовленное выражение (prepared statement) и устанавливает значения параметров.
     *
     * @param connection Подключение к базе данных.
     * @return Подготовленное выражение. Должно быть закрыто вызывающей стороной.
     * @throws SQLException При ошибке SQL.
     */
    public final PreparedStatement prepareStatement(@NotNull Connection connection) throws SQLException {
        return prepareStatement(connection, PreparedStatement.NO_GENERATED_KEYS);
    }

    /**
     * Создает подготовленное выражение (prepared statement) и устанавливает значения параметров.
     *
     * @param connection        Подключение к базе данных.
     * @param autoGeneratedKeys Значение, передаваемое в параметр <code>autoGeneratedKeys</code> метода <code>prepareStatement</code>.
     * @return Подготовленное выражение. Должно быть закрыто вызывающей стороной.
     * @throws SQLException При ошибке SQL.
     */
    public final PreparedStatement prepareStatement(@NotNull Connection connection, int autoGeneratedKeys) throws SQLException {
        //noinspection SqlSourceToSinkFlow,MagicConstant
        final PreparedStatement statement = connection.prepareStatement(getSQL(), autoGeneratedKeys);

        final List<Object> params = getParams();
        if (!params.isEmpty()) {
            for (int i = 0; i < params.size(); i++) {
                statement.setObject(i + 1, params.get(i));
            }
        }

        return statement;
    }

    /**
     * Создает подготовленное выражение и выполняет обновление (update).
     * Соединение будет получено из источника и закрыто после выполнения обновления.
     *
     * @return Результат выполнения <code>executeUpdate</code>.
     * @throws SQLException При ошибке SQL.
     */
    public final int update() throws SQLException {
        try (final Connection connection = pool.connection();
             final PreparedStatement statement = prepareStatement(connection)
        ) {
            return statement.executeUpdate();
        }
    }

    /**
     * Выполняет обновление, возвращая сгенерированные ключи.
     *
     * @param connection Подключение к базе данных.
     * @return Обертка над набором результатов (result set) со сгенерированными ключами.
     * @throws SQLException При ошибке SQL.
     */
    public final ResultSetWrapper updateWithKeys(@NotNull Connection connection) throws SQLException {
        final PreparedStatement statement = prepareStatement(connection);
        statement.closeOnCompletion();
        statement.executeUpdate();

        return new ResultSetWrapper(statement.getGeneratedKeys());
    }

    /**
     * Получает соединение из источника, выполняет обновление и возвращает сгенерированные ключи,
     * преобразованные с помощью указанного маппера.
     *
     * @param mapper Маппер.
     * @param <T>    Тип результата.
     * @return Набор результатов со сгенерированными ключами.
     * @throws SQLException При ошибке SQL.
     */
    public final <T> Optional<T> updateWithKeysAndMap(@NotNull ResultSetMapper<T> mapper) throws SQLException {
        try (final Connection connection = pool.connection();
             final ResultSetWrapper wrapper = updateWithKeys(connection)
        ) {
            return wrapper.map(mapper);
        }
    }

    /**
     * Получает соединение из источника, выполняет обновление и возвращает сгенерированные ключи,
     * преобразованные с помощью указанного маппера.
     *
     * @param mapper Маппер.
     * @param <T>    Тип элементов списка.
     * @return Набор результатов со сгенерированными ключами.
     * @throws SQLException При ошибке SQL.
     */
    public final <T> List<T> updateWithKeysAndMapAll(@NotNull ResultSetMapper<T> mapper) throws SQLException {
        try (final Connection connection = pool.connection();
             final ResultSetWrapper wrapper = updateWithKeys(connection)
        ) {
            return wrapper.mapAll(mapper);
        }
    }

    /**
     * Создает подготовленное выражение и выполняет запрос.
     *
     * @param connection Подключение к базе данных.
     * @return Обертка над набором результатов. Должна быть закрыта вызывающей стороной.
     * @throws SQLException При ошибке SQL.
     */
    public final ResultSetWrapper query(@NotNull Connection connection) throws SQLException {
        final PreparedStatement statement = prepareStatement(connection);
        final ResultSetWrapper wrapper = new ResultSetWrapper(statement.executeQuery());
        statement.closeOnCompletion();

        return wrapper;
    }

    /**
     * Получает соединение из источника, выполняет запрос, вызывает
     * {@link ResultSetWrapper#map(ResultSetMapper)} с указанным
     * маппером и возвращает результат.
     *
     * @param mapper Маппер.
     * @param <T>    Тип результата.
     * @return Результат.
     * @throws SQLException При ошибке SQL.
     */
    public final <T> Optional<T> queryAndMap(@NotNull ResultSetMapper<T> mapper) throws SQLException {
        try (final Connection connection = pool.connection();
             final ResultSetWrapper wrapper = query(connection)
        ) {
            return wrapper.map(mapper);
        }
    }

    /**
     * Получает соединение из источника, выполняет запрос, вызывает
     * {@link ResultSetWrapper#mapAll(ResultSetMapper)} с указанным
     * маппером и возвращает результат.
     *
     * @param mapper Маппер.
     * @param <T>    Тип результата.
     * @return Результат.
     * @throws SQLException При ошибке SQL.
     */
    public final <T> List<T> queryAndMapAll(@NotNull ResultSetMapper<T> mapper) throws SQLException {
        try (final Connection connection = pool.connection();
             final ResultSetWrapper wrapper = query(connection)
        ) {
            return wrapper.mapAll(mapper);
        }
    }
}
