/*
 * Copyright (c) 2026 DenaryDev
 *
 * Use of this source code is governed by an MIT-style
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/MIT.
 */
package me.denarydev.crystal.database.query;

import me.denarydev.crystal.database.connection.ConnectionPool;
import me.denarydev.crystal.database.query.set.ResultSetMapper;
import me.denarydev.crystal.database.query.set.ResultSetWrapper;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.Optional;

/**
 * Represents a SQL query with parameters for filling placeholders.
 */
public abstract class AbstractQuery {

    @NonNull
    protected final ConnectionPool pool;

    @ApiStatus.Internal
    protected AbstractQuery(@NonNull ConnectionPool pool) {
        this.pool = pool;
    }

    /**
     * @return the SQL query string.
     */
    public abstract String getSQL();

    /**
     * @return the query parameter values in the order they appear (corresponding to <code>?</code> placeholders in the SQL).
     */
    public abstract List<Object> getParams();

    /**
     * Creates a prepared statement and sets the parameter values.
     *
     * @param connection the database connection.
     * @return the prepared statement; must be closed by the caller.
     * @throws SQLException on SQL error.
     */
    @ApiStatus.Internal
    public final PreparedStatement prepareStatement(@NonNull Connection connection) throws SQLException {
        return prepareStatement(connection, PreparedStatement.NO_GENERATED_KEYS);
    }

    /**
     * Creates a prepared statement and sets the parameter values.
     *
     * @param connection        the database connection.
     * @param autoGeneratedKeys the value passed to the <code>autoGeneratedKeys</code> argument of <code>prepareStatement</code>.
     * @return the prepared statement; must be closed by the caller.
     * @throws SQLException on SQL error.
     */
    @ApiStatus.Internal
    public final PreparedStatement prepareStatement(@NonNull Connection connection, int autoGeneratedKeys) throws SQLException {
        //noinspection SqlSourceToSinkFlow,MagicConstant
        final PreparedStatement statement = connection.prepareStatement(getSQL(), autoGeneratedKeys);

        final List<Object> params = getParams();
        if (!params.isEmpty()) {
            for (int i = 0; i < params.size(); i++) {
                statement.setObject(i + 1, params.get(i));
            }
        }

        return statement;
    }

    /**
     * Prepares and executes the query as an update.
     * A connection is acquired from the pool and closed after the update completes.
     *
     * @return the result of <code>executeUpdate</code>.
     * @throws SQLException on SQL error.
     */
    public final int update() throws SQLException {
        try (final Connection connection = pool.connection();
             final PreparedStatement statement = prepareStatement(connection)
        ) {
            return statement.executeUpdate();
        }
    }

    /**
     * Executes the update and returns the generated keys.
     *
     * @param connection the database connection.
     * @return a result set wrapper containing the generated keys.
     * @throws SQLException on SQL error.
     */
    public final ResultSetWrapper updateWithKeys(@NonNull Connection connection) throws SQLException {
        final PreparedStatement statement = prepareStatement(connection, PreparedStatement.RETURN_GENERATED_KEYS);
        statement.closeOnCompletion();
        statement.executeUpdate();

        return new ResultSetWrapper(statement.getGeneratedKeys());
    }

    /**
     * Acquires a connection, executes the update, and maps the generated keys using the given mapper.
     *
     * @param mapper the result set mapper.
     * @param <T>    the result type.
     * @return the mapped generated keys.
     * @throws SQLException on SQL error.
     */
    public final <T> Optional<T> updateWithKeysAndMap(@NonNull ResultSetMapper<T> mapper) throws SQLException {
        try (final Connection connection = pool.connection();
             final ResultSetWrapper wrapper = updateWithKeys(connection)
        ) {
            return wrapper.map(mapper);
        }
    }

    /**
     * Acquires a connection, executes the update, and maps all generated keys using the given mapper.
     *
     * @param mapper the result set mapper.
     * @param <T>    the element type.
     * @return a list of mapped generated keys.
     * @throws SQLException on SQL error.
     */
    public final <T> List<T> updateWithKeysAndMapAll(@NonNull ResultSetMapper<T> mapper) throws SQLException {
        try (final Connection connection = pool.connection();
             final ResultSetWrapper wrapper = updateWithKeys(connection)
        ) {
            return wrapper.mapAll(mapper);
        }
    }

    /**
     * Creates a prepared statement and executes the query.
     *
     * @param connection the database connection.
     * @return a result set wrapper; must be closed by the caller.
     * @throws SQLException on SQL error.
     */
    public final ResultSetWrapper query(@NonNull Connection connection) throws SQLException {
        final PreparedStatement statement = prepareStatement(connection);
        final ResultSetWrapper wrapper = new ResultSetWrapper(statement.executeQuery());
        statement.closeOnCompletion();

        return wrapper;
    }

    /**
     * Acquires a connection, executes the query, and returns the first result
     * mapped by the given mapper via {@link ResultSetWrapper#map(ResultSetMapper)}.
     *
     * @param mapper the result set mapper.
     * @param <T>    the result type.
     * @return the mapped result.
     * @throws SQLException on SQL error.
     */
    public final <T> Optional<T> queryAndMap(@NonNull ResultSetMapper<T> mapper) throws SQLException {
        try (final Connection connection = pool.connection();
             final ResultSetWrapper wrapper = query(connection)
        ) {
            return wrapper.map(mapper);
        }
    }

    /**
     * Acquires a connection, executes the query, and returns all results
     * mapped by the given mapper via {@link ResultSetWrapper#mapAll(ResultSetMapper)}.
     *
     * @param mapper the result set mapper.
     * @param <T>    the result type.
     * @return the mapped results.
     * @throws SQLException on SQL error.
     */
    public final <T> List<T> queryAndMapAll(@NonNull ResultSetMapper<T> mapper) throws SQLException {
        try (final Connection connection = pool.connection();
             final ResultSetWrapper wrapper = query(connection)
        ) {
            return wrapper.mapAll(mapper);
        }
    }
}
