name: Release

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build Crystal
        run: ./gradlew build --no-daemon
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: Latest build
          files: |
            build/libs/Crystal-*.jar
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
