name: Release & Deploy

on:
  push:
    branches:
      - "v3"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build & Publish
        run: ./gradlew build publish --no-daemon -Dorg.gradle.parallel=true --stacktrace
        env:
          ORG_GRADLE_PROJECT_includeCore: true
          ORG_GRADLE_PROJECT_prostocraftUsername: ${{ secrets.DEPLOY_USERNAME }}
          ORG_GRADLE_PROJECT_prostocraftPassword: ${{ secrets.DEPLOY_PASSWORD }}
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: Latest build
          files: |
            build/libs/Crystal-*.jar
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
